spring.application.name=project-lp2
# Nome e configuração do Banco H2
spring.datasource.url=jdbc:h2:mem:projetodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Pede pro Spring criar as tabelas automaticamente com base nos seus @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o "Painel Visual" do banco de dados no seu navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
